### PR TITLE
skeleton for AppSettings

### PR DESCRIPTION
**Pull request by crcrewso**
In reference to #17, I think the best solution would be to add a settings class to quietly keep app.config updated, and to load and save from a YAML file using YamlDotNet. 

To do this, the first step is to put settings variables in App.config for both projects in the solution. I think getting some appsettings populated now would make the transition easier. 

[Instruction](https://dotnetcoretutorials.com/2021/09/21/reading-and-writing-yaml-in-c-net/)
[Source](https://github.com/aaubry/YamlDotNet)

### CODE REVIEW

**Comment by esimiele** [comment]
I'm a bit confused about what was actually changed in your fork. It looks like the beta branch was updated twice from when you forked the branch and made your changes. When I compare the two branches, it shows tons of changes in files like gitignore, project files, etc. But comparing those files using the compare tool, they look identical. Are the only real changes you made to the App.Config files? Or did you make other changes as well?

**Comment by crcrewso** [comment]
It should just be to app.config and the corresponding solution files. However I messed up by not forking my branch which is probably where all of the confusion is coming from.

**Comment by esimiele** [comment]
No worries. Hopefully it should be an easy change and you can reopen the PR

**Comment by esimiele** [comment]
FYI, I updated the beta branch today, removed the old master branch, and renamed the beta branch to 'master'. Definitely fork from the updated branch before implementing your changes again!

**Pull request closed without merging**
